### ISSUE TITLE
Cool project! Would be nice to have an example on adding an actual watcher

### ISSUE THREAD

**Issue by vesper8** [cormierm/price-notifier#1]
Very nifty project you have here. I'm checking it out. Seems like the instructions you include are all about setting up the project but don't mention anything about adding an actual website watcher. That part would be very useful. A seeder that includes a basic watcher would be equally useful!

Update: I can see you have a nice UI for creating the watchers. What I mean though is it would be nice if you wrote a little bit about all the options there and what they do. An example would be useful

**Comment by vesper8** [comment]
Trying to get it working on my Mac and the guzzle and curl fetchers work but the browsershot keeps failing with this error `Request is already handled`

Seems there's already a long opened thread regarding this error too https://github.com/puppeteer/puppeteer/issues/5334

On a side note it would be nice to know a little more about Regions.. how to add them, and how they work

**Comment by vesper8** [comment]
When I'm adding a new watcher, as I type something in the URL box I'm noticing a console error `"message": "No query results for model [App\\Template]."`

No idea what to make of that though.. and why is there a synchronous check as I'm typing the URL

**Comment by cormierm** [comment]
Thanks for checking out my project. Adding instructions is pretty low priority for me right now but I do agree an example seeder would be nice to have.

As for the 'Request is already handled' error, it does only seem to happen with browsershot and have no figured out what is causing it. I know if you run the request again a lot of time it will be successful on the following request. 

Regions allow you setup multiple servers in different regions and it will only update the watcher in the region selected. You will have to set the watcher name in the .env and then add that name to the regions table. After that you can select the region from the list when adding/editing a watcher and it will update from that watcher only.

For the Url box when adding a new watcher it does a check to see if you have any templates (domain queries) from previously added watchers for that domain and will try to auto-fill the form for you.

**Comment by vesper8** [comment]
I see! Thanks a lot for those clarifications. I've been successfully using the CurlFetcher and GuzzleFetcher. I guess those ones won't work well with sites that use Ajax but they are super fast and easy to use. Browsershot just doesn't want to work at all for me. Maybe it would work on a Linux server but it's being finicky on Macos
